### ISSUE TITLE
Problems at installation.

### ISSUE THREAD

**Issue by chodarq** [hasaru-k/GlimmaV2#22]
Hi,

I try to install your package, but have a problem:
* installing *source* package 'GlimmaV2' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object 'as.data.frame.DataTable' is not exported by 'namespace:S4Vectors'
Ejecución interrumpida
ERROR: lazy loading failed for package 'GlimmaV2'
* removing 'C:/Users/christian/Documents/R/win-library/4.0/GlimmaV2'
Error: Failed to install 'GlimmaV2' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/CHRIST~1/AppData/Local/Temp/RtmpKGXh8l/file2510511a769d/GlimmaV2_0.0.0.9000.tar.gz’ had non-zero exit status

If I try to install fro the gz file generated, I obtain the same results. I'm using R v4.0.2 under Win10.
Any help? 
Thanks!

Christian.

**Comment by chodarq** [comment]
Seems that problem comes from the Bioconductor version. In the new releases, 3.12, S4Vectors don't get the function as.data.frame.DataTable(). I downgrade BioC to 3.11 and the installation work.
So, all working now.

**Comment by hasaru-k** [comment]
Hi Christian,

I've gotten rid of the dependency on S4Vectors::as.data.frame.DataTable in the latest commit on master. It should install correctly on BioC devel branch now. Thanks for pointing this out!

Thanks,
Hasaru
