### ISSUE TITLE
Jitter Points 

### ISSUE THREAD

**Issue by danphillips28** [hasaru-k/GlimmaV2#75]
Hey! Thanks for making Glimma2, I already use it a lot and I love it! 

I have one suggestion. This is to jitter points in the gene-level summary plots, as was the case for glimma1. Jitter is really helpful when you have lots of data points in each contrast, as I do. 

Thanks again!
Dan

**Comment by Shians** [comment]
Thanks for the suggestion Dan. This may be supported in the near future, I think some recent update to the vega library may have made this possible, though it's not yet been released.

https://github.com/vega/vega-lite/pull/7684
