### ISSUE TITLE
Deseq2 no negative logCPM

### ISSUE THREAD

**Issue by Pahi95** [hasaru-k/GlimmaV2#76]
Hi!

I really love your work!
I'm doing a paralel analysis with deseq2 and edgeR, and when I plot the results, I don't get negative logCPM values for the Deseq dataset, but there should be, becouse if I do an individual table to check the cpm values, there are negative ones.

Can you please help? Thank you!

**Comment by hasaru-k** [comment]
Hey there! Sorry for the belated reply, and thanks so much!

Is the issue that DESeq2 isn't plotting negative logCPM values as expected? If so, I'd direct you to https://github.com/mikelove/DESeq2/issues/ as that's a different package :)

**Comment by hasaru-k** [comment]
hey @Pahi95, pls feel free to reopen if this is still an issue
