### ISSUE TITLE
GlimmaXY() does not extract gene names from supplied vectors properly

### ISSUE THREAD

**Issue by nghiaagent** [hasaru-k/GlimmaV2#88]
Hi!

`glimmaXY()` suggests the user to supply vectors for `x` and `y`, however the current code extracts gene names using `rownames()`, which doesn't work on vectors, causing to the produced graph to lack gene names. A simple fix would be to use `names()` instead.

```
  # add rownames to LHS of table
  if (!is.null(counts)) {
    table <- cbind(gene=rownames(counts), table)
  } else if (!is.null(rownames(x))) {
    table <- cbind(gene=rownames(x), table)
  } else if (!is.null(rownames(y))) {
    table <- cbind(gene=rownames(y), table)
  } else {
    table <- cbind(gene=seq_along(x), table)
  }
````

**Comment by jdrnevich** [comment]
I am also having this issue in using glimmaXY() - it would be nice to have the gene symbols pop up like they do in glimmaMA/glimmaVolcano

**Comment by nghiaagent** [comment]
> I am also having this issue in using glimmaXY() - it would be nice to have the gene symbols pop up like they do in glimmaMA/glimmaVolcano

I eventually found a solution! All you have to do is coerce the vector into a dataframe with 1 column and add rownames to it. For example:

```
  # Coerce vector (for example results$log2FoldChange) to dataframe
  x <- as.data.frame(results$log2FoldChange) 
  
  # Add rownames to the vector
  rownames(x) <- names
```

I note that this has to be base R dataframes, not tibbles, since tibbles do not support rownames.

**Comment by hasaru-k** [comment]
will close this as it's been fixed by @nghiaagent's very neat solution in https://github.com/hasaru-k/GlimmaV2/pull/96 :) thank you
