### ISSUE TITLE
Blank plot when gene annotation only contains one column

### ISSUE THREAD

**Issue by Shians** [hasaru-k/GlimmaV2#90]
```
library(Glimma)
dge <- readRDS(system.file("RNAseq123/dge.rds", package = "Glimma"))

design <- readRDS(
    system.file("RNAseq123/design.rds", package = "Glimma"))
contr.matrix <- readRDS(
    system.file("RNAseq123/contr.matrix.rds", package = "Glimma"))

dge <- estimateDisp(dge, design)
gfit <- glmFit(dge, design)
glrt <- glmLRT(gfit, design, contrast = contr.matrix)
glrt$genes <- glrt$genes[, -(2:3), drop = FALSE]
colnames(glrt$gene) <- "gene"
glimmaMA(glrt)
```

Error message in browser console:

```
index.html?capabilities=1&host=http%3A%2F%2F127.0.0.1%3A21379:2902 Uncaught TypeError: xyData.annoCols.map is not a function
    at createXYSpec (index.html?capabilities=1&host=http%3A%2F%2F127.0.0.1%3A21379:2902:39)
```

Offending line at https://github.com/hasaru-k/GlimmaV2/blob/09241f6efdbfc2f8efb7e2aea7005be781bd3848/inst/htmlwidgets/lib/GlimmaV2/XYSpecs.js#L9

The issue is that when the gene annotation only has one column, `xyData.annoCols` is just a string and not a vector, leading to the `map` method to not exist. A quick fix might be to detect the single string and coerce it to a length 1 vector just before this line, I'm not familiar enough with the codebase at this moment to know if it makes more sense to perform the coercion further upstream.

**Comment by hasaru-k** [comment]
thanks @Shians! the `annoCols` argument does indeed look like a vector (e.g. `["gene"]`) right up until it's passed from R into the HTMLwidgets framework, and then in the JSON conversion step it gets converted into a string - so I think the earliest we can rectify it is where you mentioned, unless we can find a way to stop HTMLwidgets from converting single element vectors into strings

Have put up a fix at https://github.com/hasaru-k/GlimmaV2/pull/102

**Comment by hasaru-k** [comment]
update - core issue is that lists with single element vectors get converted into strings in the JSON conversion step
<img width="386" alt="image" src="https://github.com/user-attachments/assets/fdf24d07-09d8-4454-accd-a4e2ee9e908a" />
