### ISSUE TITLE
glimmaVolcano p.adj.method not automatically carried over to status' decideTests function

### ISSUE THREAD

**Issue by IgnatiusPang** [hasaru-k/GlimmaV2#94]
For glimmaVolcano.MArrayLM ,

if I change the param  p.adj.method equal to "none"

it doesn't automatically carry over to the param status  status=decideTests(x, adjust.method="none")

Would you be able to make a change to carry it over please?

This may mean changing the code to something like 

status = decideTests(x, adjust.method=p.adj.method)

**Comment by hasaru-k** [comment]
thanks @IgnatiusPang, should be fixed following https://github.com/hasaru-k/GlimmaV2/pull/101
