### ISSUE TITLE
Add min_y_axis to glimmaXY/glimmaMA/glimmaVolcano?

### ISSUE THREAD

**Issue by jdrnevich** [hasaru-k/GlimmaV2#95]
Hello! I've love the Glimma package since it came out. The older glMDPlot() would auto-scale the top right expression plot to the range of data whereas the newer glimmaXY/glimmaMA/glimmaVolcano plots will always start at 0 unless the lowest values are negative. The new plots have a max_y_axis but not a corresponding min_y_axis function. For highly expressed genes, this makes the top right plot almost worthless. The attached is taken from https://bioconductor.org/packages/release/bioc/vignettes/Glimma/inst/doc/limma_edger.html#, for gene Eef2
![vega-export (1)](https://github.com/user-attachments/assets/b1c420ea-2dcf-49ef-abf5-76cd21982563). Having a min_y_axis would be crucial for genes like this.

Thanks in advance,
Jenny

**Comment by hasaru-k** [comment]
Hi @jdrnevich, happy to report that this has been added in https://github.com/hasaru-k/GlimmaV2/issues/87 🙂 if you reinstall via `devtools::install_github("hasaru-k/GlimmaV2")` you should be able to see the new `Y min` input element
