### ISSUE TITLE
Plot controls are vertical in markdown documents for glimmaMDS

### ISSUE THREAD

**Issue by jmacdon** [hasaru-k/GlimmaV2#99]
See any of the vignettes. The plot controls are now rendered on top of the text below. If you simply save as a separate HTML document it's fine.

**Comment by hasaru-k** [comment]
thank you for reporting this @jmacdon, fix is in progress at https://github.com/hasaru-k/GlimmaV2/pull/100

**Comment by hasaru-k** [comment]
this should be addressed now! please reinstall via `devtools::install_github("hasaru-k/GlimmaV2")` and let me know if there are any issues :)

**Comment by jmacdon** [comment]
Are you going to push to the release and devel versions on Bioconductor?

**Comment by Shians** [comment]
I will handle that some time this week. Sorry we are currently in an awkward set-up where I am the maintainer but Has is the one familiar with the codebase.

**Comment by hasaru-k** [comment]
We have now pushed to the devel version on Bioconductor
